baseURL: https://drone-runner-exec.netlify.com #/runner/exec
languageCode: en-us
title: Drone Exec Runner
theme: drone-hugo-theme

googleAnalytics: "UA-34247933-4"

params:
  algolia_key: 745aeaa8be75dc0c4de55030703ed3f4
  algolia_index: drone_io

pygmentsUseClasses: true
pygmentsCodefences: true
